module.exports = [
  require('./apps/core/wcm/components/accordion/v1/accordion/.content.xml'),
  require('./apps/core/wcm/components/breadcrumb/v1/breadcrumb/.content.xml'),
  require('./apps/core/wcm/components/breadcrumb/v2/breadcrumb/.content.xml'),
  require('./apps/core/wcm/components/button/v1/button/.content.xml'),
  require('./apps/core/wcm/components/carousel/v1/carousel/.content.xml'),
  require('./apps/core/wcm/components/container/v1/container/.content.xml'),
  require('./apps/core/wcm/components/contentfragment/v1/contentfragment/.content.xml'),
  require('./apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/.content.xml'),
  require('./apps/core/wcm/components/download/v1/download/.content.xml'),
  require('./apps/core/wcm/components/embed/v1/embed/.content.xml'),
  require('./apps/core/wcm/components/embed/v1/embed/embeddable/.content.xml'),
  require('./apps/core/wcm/components/embed/v1/embed/embeddable/youtube/.content.xml'),
  require('./apps/core/wcm/components/experiencefragment/v1/experiencefragment/.content.xml'),
  require('./apps/core/wcm/components/form/button/v1/button/.content.xml'),
  require('./apps/core/wcm/components/form/button/v2/button/.content.xml'),
  require('./apps/core/wcm/components/form/container/v1/container/.content.xml'),
  require('./apps/core/wcm/components/form/container/v2/container/.content.xml'),
  require('./apps/core/wcm/components/form/hidden/v1/hidden/.content.xml'),
  require('./apps/core/wcm/components/form/hidden/v2/hidden/.content.xml'),
  require('./apps/core/wcm/components/form/options/v1/options/.content.xml'),
  require('./apps/core/wcm/components/form/options/v2/options/.content.xml'),
  require('./apps/core/wcm/components/form/text/v1/text/.content.xml'),
  require('./apps/core/wcm/components/form/text/v2/text/.content.xml'),
  require('./apps/core/wcm/components/image/v1/image/.content.xml'),
  require('./apps/core/wcm/components/image/v2/image/.content.xml'),
  require('./apps/core/wcm/components/languagenavigation/v1/languagenavigation/.content.xml'),
  require('./apps/core/wcm/components/list/v1/list/.content.xml'),
  require('./apps/core/wcm/components/list/v2/list/.content.xml'),
  require('./apps/core/wcm/components/navigation/v1/navigation/.content.xml'),
  require('./apps/core/wcm/components/page/v1/page/.content.xml'),
  require('./apps/core/wcm/components/page/v2/page/.content.xml'),
  require('./apps/core/wcm/components/pdfviewer/v1/pdfviewer/.content.xml'),
  require('./apps/core/wcm/components/progressbar/v1/progressbar/.content.xml'),
  require('./apps/core/wcm/components/search/v1/search/.content.xml'),
  require('./apps/core/wcm/components/separator/v1/separator/.content.xml'),
  require('./apps/core/wcm/components/sharing/v1/sharing/.content.xml'),
  require('./apps/core/wcm/components/tabs/v1/tabs/.content.xml'),
  require('./apps/core/wcm/components/teaser/v1/teaser/.content.xml'),
  require('./apps/core/wcm/components/text/v1/text/.content.xml'),
  require('./apps/core/wcm/components/text/v2/text/.content.xml'),
  require('./apps/core/wcm/components/title/v1/title/.content.xml'),
  require('./apps/core/wcm/components/title/v2/title/.content.xml'),
  // require('./libs/wcm/foundation/components/responsivegrid/.content.xml'),
  // require('./libs/wcm/foundation/components/parsys/.content.xml'),
  // require('./libs/wcm/foundation/components/parsys/allowedcomponents/.content.xml'),
  // require('./libs/wcm/foundation/components/parsys/newpar/.content.xml'),
];